config/routes.rb
Rails.application.routes.draw do
  root 'curbrockpaperscissors#index'

  get '/play', to: 'curbrockpaperscissors#play'
  get '/choice/:state', to: 'curbrockpaperscissors#choice', as: :choice
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/curbrockpaperscissors_controller.rb
class CurbrockpaperscissorsController < ApplicationController
  def index
  end

  def play
  end

  def choice
    @player_choice = permit_params(params)[:state]
    @api_choice = ApiGetResult.call || 'keeps silence'
    @winner = GetGameResult.call(@player_choice, @api_choice)
  end

  private

  def permit_params(params)
    params.permit(:state)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/curbrockpaperscissors_helper.rb
module CurbrockpaperscissorsHelper
end

app/views/curbrockpaperscissors/choice.html.erb
<div>
  <p> Your choice is</p>
  <%= @player_choice %>
  <p> API\'s choice is</p>
  <%= @api_choice %>
  <p> The winner is </p>
  <%= @winner %>
  </br>
  <a href="<%= root_path %>">Run again</a>
</div>

app/views/curbrockpaperscissors/index.html.erb
<div>
  <h1> Hello </h1>
  <p> For start click PLAY </p>
  <a href="<%= play_path %>">Play</a>
</div>

app/views/curbrockpaperscissors/play.html.erb
<div>
  <p> Choose rock OR paper OR scissors</p>
  <a href="<%= choice_path(:rock) %>">Rock</a>
  <a href="<%= choice_path(:paper) %>">Paper</a>
  <a href="<%= choice_path(:scissors) %>">Scissors</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Curbrockpaperscissors</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>